apiVersion: apps/v1beta1 #for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.5-alpine
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
